// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/connect": {
            "get": {
                "description": "Возвращает текущий пул активных MTConnect подключений.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Получить список подключений",
                "responses": {
                    "200": {
                        "description": "Список активных подключений",
                        "schema": {
                            "$ref": "#/definitions/models.GetConnectionsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новое подключение к станку по его EndpointURL и модели.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Создать подключение",
                "parameters": [
                    {
                        "description": "Данные для подключения",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание подключения",
                        "schema": {
                            "$ref": "#/definitions/models.CreateConnectionResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет подключение из пула и базы данных по его SessionID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Удалить подключение",
                "parameters": [
                    {
                        "description": "ID сессии для удаления",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном удалении",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Подключение не найдено",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/connect/check": {
            "post": {
                "description": "Проверяет доступность эндпоинта, связанного с указанным SessionID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Проверить состояние подключения",
                "parameters": [
                    {
                        "description": "ID сессии для проверки",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статус 'healthy'",
                        "schema": {
                            "$ref": "#/definitions/models.CheckConnectionResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Статус 'unhealthy'",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/polling/start": {
            "post": {
                "description": "Запускает периодический сбор данных для подключения по SessionID с заданным интервалом.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polling"
                ],
                "summary": "Запустить опрос",
                "parameters": [
                    {
                        "description": "Параметры для запуска опроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PollingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешном запуске",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/polling/stop": {
            "post": {
                "description": "Останавливает сбор данных для подключения по SessionID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polling"
                ],
                "summary": "Остановить опрос",
                "parameters": [
                    {
                        "description": "ID сессии для остановки опроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение об успешной остановке",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CheckConnectionResponse": {
            "type": "object",
            "properties": {
                "Status": {
                    "type": "string",
                    "example": "healthy"
                },
                "connectionInfo": {
                    "$ref": "#/definitions/models.ConnectionInfo"
                }
            }
        },
        "models.ConnectionConfig": {
            "type": "object",
            "properties": {
                "EndpointURL": {
                    "type": "string"
                },
                "Manufacturer": {
                    "type": "string"
                },
                "Model": {
                    "type": "string"
                }
            }
        },
        "models.ConnectionInfo": {
            "type": "object",
            "properties": {
                "Config": {
                    "$ref": "#/definitions/models.ConnectionConfig"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "IsHealthy": {
                    "type": "boolean"
                },
                "LastUsed": {
                    "type": "string"
                },
                "SessionID": {
                    "type": "string"
                },
                "UseCount": {
                    "type": "integer"
                }
            }
        },
        "models.ConnectionRequest": {
            "type": "object",
            "required": [
                "EndpointURL",
                "Model"
            ],
            "properties": {
                "EndpointURL": {
                    "type": "string"
                },
                "Manufacturer": {
                    "type": "string"
                },
                "Model": {
                    "type": "string"
                }
            }
        },
        "models.CreateConnectionResponse": {
            "type": "object",
            "properties": {
                "Status": {
                    "type": "string",
                    "example": "ok"
                },
                "connectionInfo": {
                    "$ref": "#/definitions/models.ConnectionInfo"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "Status": {
                    "type": "string",
                    "example": "error"
                },
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 404
                        },
                        "message": {
                            "type": "string",
                            "example": "Подключение не найдено"
                        }
                    }
                }
            }
        },
        "models.GetConnectionsResponse": {
            "type": "object",
            "properties": {
                "Connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConnectionInfo"
                    }
                },
                "PoolSize": {
                    "type": "integer",
                    "example": 2
                },
                "Status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string",
                    "example": "Polling started successfully"
                },
                "Status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.PollingRequest": {
            "type": "object",
            "required": [
                "Interval",
                "SessionID"
            ],
            "properties": {
                "Interval": {
                    "description": "в миллисекундах",
                    "type": "integer"
                },
                "SessionID": {
                    "type": "string"
                }
            }
        },
        "models.SessionRequest": {
            "type": "object",
            "required": [
                "SessionID"
            ],
            "properties": {
                "SessionID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "MTConnect Service API",
	Description:      "API для работы с протоколом MTConnect и отправки данных в Kafka.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
